### ISSUE TITLE
Cannot setup integration on 2024.1.2

### ISSUE THREAD

**Issue by rbnmk** [joselcaguilar/azure-openai-ha#72]
I am currently on the latest Home Assistant version and cannot setup this integration. I have a working OpenAI instance on Azure.

Core: 2024.1.2
Supervisor: 2023.12.0
Operating System: 11.4

I get the following error:

`2024-01-10 09:20:53.403 ERROR (MainThread) [custom_components.azure_openai_conversation.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/azure_openai_conversation/config_flow.py", line 91, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/azure_openai_conversation/config_flow.py", line 71, in validate_input
    await hass.async_add_executor_job(partial(openai.Model.list, request_timeout=10))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
openai.lib._old_api.APIRemovedInV1: 
You tried to access openai.Model, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 
Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742`

**Comment by garyneville** [comment]
Same!

**Comment by kiloptero** [comment]
same

**Comment by joselcaguilar** [comment]
@rbnmk @garyneville @kiloptero So sorry guys, unfortunately, due to personal reasons I was not able to maintain this repo, other priorities coming up.
I would like to inform that it will be updated to support the latest **HA 2025.1.0** in the following days 😊🥳
